import { Property, SiteConfig } from "./types";

export const SITE_CONFIG: SiteConfig = {
  contact_phone: "+91-9876543210",
  contact_email: "info@realitywize.com",
  whatsapp_number: "919876543210",
  office_address: "Plot 22, Sector 150, Noida Expressway, UP 201310",
};

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "the-emerald-estate",
    title: "The Emerald Estate",
    subtitle: "Premium Eco-Certified Living",
    description: "A luxurious estate nestled in Sector 150, near Central Park. Features premium eco-certified construction with sustainable materials and lush green surroundings.",
    type: "Residential",
    subtype: "Bungalow/Villa",
    transaction_type: "Sale",
    price: "3.4 Cr",
    area: 4500,
    area_type: "SqFt",
    facing: "East",
    floor: null,
    bedrooms: 5,
    status: "New",
    address: "Sector 150, Noida, Near Central Park",
    pincode: "201310",
    city: "Noida",
    state: "Uttar Pradesh",
    maps_link: "https://maps.google.com/?q=Sector+150+Noida",
    tags: ["Premium", "Eco-Certified"],
    images: [
      { id: "1a", url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCczT_f7-34sa69IctHVblIBM5BQpqgq1pUn2a2Q_C5jQ9lkxPpVBwD_NNZ77kD9IXxzo3Ph9jY8e3oM94mUW82MDvKlJ_giAdOGjGJbWwEY82ByzdThYABHjgZ8CM1gIovbio5Me1j6i8Q4Y9ouUIdBtBLow3OKgT9VECPaavWndtTLbhp2HhsVDAqVu6r2kOVnKhzL7LLvRX_khm70a2ZlmT_ETRfvl_JN0oS2vG5bHHcvW8eNkSixE1rC7e76YqvmNvuJO0LYk35", alt_text: "The Emerald Estate exterior", sort_order: 0, is_primary: true },
    ],
    is_sold: false,
    is_active: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    slug: "oakwood-residences",
    title: "Oakwood Residences",
    subtitle: "Riverside Living at Its Finest",
    description: "Elegant residences with panoramic riverside views in Sector 128. Modern architecture blended with natural surroundings for a tranquil living experience.",
    type: "Residential",
    subtype: "Apartment",
    transaction_type: "Sale",
    price: "75 Lakhs",
    area: 1200,
    area_type: "SqFt",
    facing: "North",
    floor: "3rd",
    bedrooms: 2,
    status: "New",
    address: "Sector 128, Noida, Riverside Views",
    pincode: "201304",
    city: "Noida",
    state: "Uttar Pradesh",
    maps_link: "https://maps.google.com/?q=Sector+128+Noida",
    tags: ["Riverside"],
    images: [
      { id: "2a", url: "https://lh3.googleusercontent.com/aida-public/AB6AXuBtuIrR7-ZOVUG9uUtNpm_k4q1G27leMzokoAP0xag3J5JR1xptKj8XdIIImPUn7yW-oZBtuZ8icBtn17s8S79l-9afCjzpI0KMLD1vUaA2Dylj5hB2Ok6x23n2xfTJnuF1mMcyZs2R2qKZ3Ru2th3zZFbbCtdOjwpKmVyNfc3IxoAfxNvVN7xDmwL2Deu5oSDxUOlN7DZbqobqSJOXVkfrSryDuu60_6D3cq7Yn7_lj0IunZLl3qrJi_HH58zEUB8HZa2b5-SNRVvx", alt_text: "Oakwood Residences exterior", sort_order: 0, is_primary: true },
    ],
    is_sold: false,
    is_active: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    slug: "the-moss-pavilion",
    title: "The Moss Pavilion",
    subtitle: "Forest Edge Luxury",
    description: "An architectural marvel on the forest edge of Sector 94. Floor-to-ceiling windows frame ancient trees while sustainable design ensures harmony with nature.",
    type: "Residential",
    subtype: "Bungalow/Villa",
    transaction_type: "Sale",
    price: "1.8 Cr",
    area: 3200,
    area_type: "SqFt",
    facing: "West",
    floor: null,
    bedrooms: 4,
    status: "New",
    address: "Sector 94, Noida, Forest Edge",
    pincode: "201301",
    city: "Noida",
    state: "Uttar Pradesh",
    maps_link: "https://maps.google.com/?q=Sector+94+Noida",
    tags: ["Forest Edge"],
    images: [
      { id: "3a", url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDAf89A6vZsshIqsSchXQUZVjS4fxehtadUPDnOHRf80VL_cqLsvqKXJQRFzei0e4nkJNPls76TB-cCGyBYLdtkmG1DFrTiXOVYXX_2rLltVP6B5c-1aPw5H0HSoyBYxTz9tE7r-8KjMVnMAx4QK1vm6dYaaKw5JtL2o4Sk1t982K9ZgEkgRNDQ5icXiDTbIhBpVaAzi6etIue1LNM68JuJTYq23RpPxbTfa7yd5Nbm1EKE90T5ybxgnH-fg_aRw49G6PITalRohdMO", alt_text: "The Moss Pavilion exterior", sort_order: 0, is_primary: true },
    ],
    is_sold: false,
    is_active: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    slug: "verdant-sky-villas",
    title: "Verdant Sky-Villas",
    subtitle: "Limited Edition Penthouses",
    description: "Duplex penthouses with private terrace gardens and panoramic views of the city skyline draped in green. A limited edition collection for the discerning few.",
    type: "Residential",
    subtype: "Apartment",
    transaction_type: "Sale",
    price: "5.2 Cr",
    area: 6000,
    area_type: "SqFt",
    facing: "South",
    floor: "Top Floor",
    bedrooms: 6,
    status: "New",
    address: "Sector 150, Noida",
    pincode: "201310",
    city: "Noida",
    state: "Uttar Pradesh",
    maps_link: "https://maps.google.com/?q=Sector+150+Noida",
    tags: ["Limited Edition", "Penthouse"],
    images: [
      { id: "4a", url: "https://lh3.googleusercontent.com/aida-public/AB6AXuBwN1m3feYjBuWDYRhDnl5PuUx9YIcxkf64SZuUrKBm3-LnRL2YIMrKfyMSG7uP627SAyUnOH-IhetZHYn-AeFbQIJ-VYLtm4iWmSNIjm_Hi7uD8HPrsvqngc1d2T5WukecvJiHKA7ceG_my98B_qx0hFT6zsAl3vincLjB4a9a2mnYWI_mDjLKDX7q75DTQE4KCI_D1AGN2mYFyR6rhrFH1mpslywMZfYH8gR98OQDd7R1lZva8L9HEtIU8gp61YriKWUUiR5nJ6G-", alt_text: "Verdant Sky-Villas exterior", sort_order: 0, is_primary: true },
    ],
    is_sold: false,
    is_active: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    slug: "sector-62-commercial-office",
    title: "Prime Commercial Office Space",
    subtitle: "IT Hub Location",
    description: "Premium office space in the heart of Noida's IT corridor. Fully furnished with modern amenities, high-speed elevators, and 24/7 security.",
    type: "Commercial",
    subtype: "Office",
    transaction_type: "Lease",
    price: "45 Lakhs/yr",
    area: 2500,
    area_type: "SqFt",
    facing: null,
    floor: "8th",
    bedrooms: null,
    status: "Furnished",
    address: "Sector 62, Noida",
    pincode: "201309",
    city: "Noida",
    state: "Uttar Pradesh",
    maps_link: null,
    tags: ["IT Corridor", "Furnished"],
    images: [
      { id: "5a", url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCPMck7ip76QWbLtRNn4H9v6T_Ccu-J4ltSzPrv5LswPVH0BG7LpJf84yDmTRMIu775aDPjKJjxZtrAdvGeceYtVMoJiq1WMNz60Q7fykhRktQn48y4nbGHzl_U8g8u0qYcTR0gUmTly8rGOAjtQ_xHCkR7PcfOpwVuD-SAUizRONq0P89uEnbZBhh4wJptW86q5y5Qm80w9XiB1jX-e0YX1Hw_X_g01lov2UaDbIIknohRjUOTkaEPH9yBRucTf_UumkTxCZiUG5J6", alt_text: "Commercial office space", sort_order: 0, is_primary: true },
    ],
    is_sold: false,
    is_active: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    slug: "industrial-warehouse-sector-80",
    title: "Industrial Warehouse",
    subtitle: "Large Format Storage",
    description: "Spacious warehouse facility with loading docks, high ceilings, and easy access to Noida Expressway. Ideal for logistics and distribution.",
    type: "Industrial",
    subtype: "Warehouse/Godown",
    transaction_type: "Lease",
    price: "25 Lakhs/yr",
    area: 10000,
    area_type: "SqFt",
    facing: null,
    floor: "Ground",
    bedrooms: null,
    status: "Bare-Shell",
    address: "Sector 80, Noida",
    pincode: "201305",
    city: "Noida",
    state: "Uttar Pradesh",
    maps_link: null,
    tags: ["Expressway Access"],
    images: [
      { id: "6a", url: "https://lh3.googleusercontent.com/aida-public/AB6AXuDENix6kyl3cuiaOqboPVrV8ceyGbru_NgZQ28DbkHZGPr_r6vjAqGwjt-dIRFQvfxtYCai9qTaVlYkyMyQ-5oZUSjdt1u7CNSI6gEeI2SHmkKKGO7ZHVunKJH7RSiCigF-lvrytskbKb2KYKWQMkZzzb1K_a4WIVo2EM_SdTAtqbtJh-crazNX3E61jYc5CsQ2CwGg13cSalf9NufOeXDdzduNd1fd_FoHMus7feud1Ahc3ZzGUfGIrlOiK-ACw3kTkn0PKTbOcfFo", alt_text: "Industrial warehouse", sort_order: 0, is_primary: true },
    ],
    is_sold: false,
    is_active: true,
    is_featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
